module.exports = () => { 
  const items=[
  { id:'1',type: 'clothe',size: 's',gender: 'man', typeClothe: 'shirt',price:'3000',location: './imgShop/img1.png'},
  { id:'2',type: 'clothe',size: 's',gender: 'man', typeClothe: 'cropeTop',price:'3000',location: './imgShop/img2.png'},
  { id:'3',type: 'clothe',size: 'm',gender: 'woman', typeClothe: 'sweatshirt',price:'3000',location: './imgShop/img6.png'},
  { id:'4',type: 'clothe',size: 'm',gender: 'woman', typeClothe: 'shirt',price:'3000',location: './imgShop/img9.png'},
  { id:'6',type: 'clothe',size: 'm',gender: 'woman', typeClothe: 'shirt',price:'3000',location: './imgShop/img7.png'},
  { id:'7',type: 'clothe',size: 'm',gender: 'woman', typeClothe: 'shirt',price:'3000',location: './imgShop/img8.png'},
  { id:'8',type: 'clothe',size: 'm',gender: 'woman', typeClothe: 'shirt',price:'3000',location: './imgShop/img10.png'},
  { id:'10',type: 'clothe',size: 'l',gender: 'woman', typeClothe: 'sweatshirt',price:'3000',location: './imgShop/img11.png'},
  { id:'11',type: 'clothe',size: 'l',gender: 'woman', typeClothe: 'sweatshirt',price:'3000',location: './imgShop/img12.png'},
  { id:'12',type: 'clothe',size: 'l',gender: 'woman', typeClothe: 'sweatshirt',price:'3000',location: './imgShop/img13.png'},
  { id:'13',type: 'clothe',size: 'l',gender: 'woman', typeClothe: 'sweatshirt',price:'3000',location: './imgShop/img14.png'},
  { id:'14',type: 'clothe',size: 'l',gender: 'woman', typeClothe: 'sweatshirt',price:'3000',location: './imgShop/img15.png'},
  { id:'15',type: 'clothe',size: 'l',gender: 'woman', typeClothe: 'sweatshirt',price:'3000',location: './imgShop/img16.png'},
  // { id:'16',type: 'clothe',size: 'l',gender: 'woman', typeClothe: 'sweatshirt',price:'3000',location: './imgShop/img17.png'},
  // { id:'17',type: 'clothe',size: 'l',gender: 'woman', typeClothe: 'sweatshirt',price:'3000',location: './imgShop/img18.png'},
  // { id:'18',type: 'clothe',size: 'l',gender: 'woman', typeClothe: 'sweatshirt',price:'3000',location: './imgShop/img19.png'},
  { id:'19',type: 'clothe',size: 'l',gender: 'woman', typeClothe: 'sweatshirt',price:'3000',location: './imgShop/img3.png'},
  { id:'20',type: 'clothe',size: 'l',gender: 'woman', typeClothe: 'cropeTop',price:'3000',location: './imgShop/img4.png'},
  { id:'21',type: 'clothe',size: 'l', gender: 'woman', typeClothe: 'cropeTop',price:'3000',location: './imgShop/img5.png'},
  { id:'23',type: 'wop',name: 'Spring4',price:'3000',location: './imgShop/img34.jpeg'},
  { id:'24',type: 'wop',name: 'Spring4',price:'3000',location: './imgShop/img35.jpeg'},
  { id:'33',type: 'wop',name: 'Spring4',price:'3000',location: './imgShop/img36.jpeg'},
  { id:'25',type: 'wop',name: 'Spring4',price:'3000',location: './imgShop/img37.jpeg'},
  { id:'26',type: 'wop',name: 'Spring4',price:'3000',location: './imgShop/img38.jpeg'},
  { id:'27',type: 'wop',name: 'Spring4',price:'3000',location: './imgShop/img39.jpeg'},
  { id:'29',type: 'ceramics',name: 'Spring4',price:'3000',location: './imgShop/img41.jpg'},
  { id:'30',type: 'ceramics',name: 'Spring4',price:'3000',location: './imgShop/img42.jpg'},
  { id:'31',type: 'ceramics',name: 'Spring4',price:'3000',location: './imgShop/img43.jpg'},
  { id:'32',type: 'ceramics',name: 'Spring4',price:'3000',location: './imgShop/img44.jpg'},
  ]
  return items;
}