module.exports = () => { 
    const shopPieces=[
      { id:'1',type: 'clothe',size: 's',gender: 'man', typeClothe: 'shirt',price:'3000',location: './img/img1.png'},
      { id:'2',type: 'clothe',size: 's',gender: 'man', typeClothe: 'cropeTop',price:'3000',location: './img/img2.png'},
      { id:'3',type: 'clothe',size: 'm',gender: 'woman', typeClothe: 'sweatshirt',price:'3000',location: './img/img6.png'},
      { id:'4',type: 'clothe',size: 'm',gender: 'woman', typeClothe: 'shirt',price:'3000',location: './img/img9.png'},
      { id:'6',type: 'clothe',size: 'm',gender: 'woman', typeClothe: 'shirt',price:'3000',location: './img/img7.png'},
      { id:'7',type: 'clothe',size: 'm',gender: 'woman', typeClothe: 'shirt',price:'3000',location: './img/img8.png'},
      { id:'8',type: 'clothe',size: 'm',gender: 'woman', typeClothe: 'shirt',price:'3000',location: './img/img10.png'},
      { id:'10',type: 'clothe',size: 'l',gender: 'woman', typeClothe: 'sweatshirt',price:'3000',location: './img/img11.png'},
      { id:'11',type: 'clothe',size: 'l',gender: 'woman', typeClothe: 'sweatshirt',price:'3000',location: './img/img12.png'},
      { id:'12',type: 'clothe',size: 'l',gender: 'woman', typeClothe: 'sweatshirt',price:'3000',location: './img/img13.png'},
      { id:'13',type: 'clothe',size: 'l',gender: 'woman', typeClothe: 'sweatshirt',price:'3000',location: './img/img14.png'},
      { id:'14',type: 'clothe',size: 'l',gender: 'woman', typeClothe: 'sweatshirt',price:'3000',location: './img/img15.png'},
      { id:'15',type: 'clothe',size: 'l',gender: 'woman', typeClothe: 'sweatshirt',price:'3000',location: './img/img16.png'},
      // { id:'16',type: 'clothe',size: 'l',gender: 'woman', typeClothe: 'sweatshirt',price:'3000',location: './img/img17.png'},
      // { id:'17',type: 'clothe',size: 'l',gender: 'woman', typeClothe: 'sweatshirt',price:'3000',location: './img/img18.png'},
      // { id:'18',type: 'clothe',size: 'l',gender: 'woman', typeClothe: 'sweatshirt',price:'3000',location: './img/img19.png'},
      { id:'19',type: 'clothe',size: 'l',gender: 'woman', typeClothe: 'sweatshirt',price:'3000',location: './img/img3.png'},
      { id:'20',type: 'clothe',size: 'l',gender: 'woman', typeClothe: 'cropeTop',price:'3000',location: './img/img4.png'},
      { id:'21',type: 'clothe',size: 'l', gender: 'woman', typeClothe: 'cropeTop',price:'3000',location: './img/img5.png'},
      { id:'23',type: 'wop',name: 'Spring4',price:'3000',location: './img/img34.jpeg'},
      { id:'24',type: 'wop',name: 'Spring4',price:'3000',location: './img/img35.jpeg'},
      { id:'25',type: 'wop',name: 'Spring4',price:'3000',location: './img/img37.jpeg'},
      { id:'26',type: 'wop',name: 'Spring4',price:'3000',location: './img/img38.jpeg'},
      { id:'27',type: 'wop',name: 'Spring4',price:'3000',location: './img/img39.jpeg'},
      { id:'28',type: 'ceramics',name: 'Spring4',price:'3000',location: './img/img40.jpg'},
      { id:'29',type: 'ceramics',name: 'Spring4',price:'3000',location: './img/img41.jpg'},
      { id:'30',type: 'ceramics',name: 'Spring4',price:'3000',location: './img/img42.jpg'},
      { id:'31',type: 'ceramics',name: 'Spring4',price:'3000',location: './img/img43.jpg'},
      { id:'32',type: 'ceramics',name: 'Spring4',price:'3000',location: './img/img44.jpg'},
    ]
    return shopPieces;
  }