module.exports = () => { 
  const art=[
    { id:'1',type: 'painting',size: '180x120',title: 'Spring1', year: '2020', technique: 'Acrilic',location: 'img1.jpeg',locationFullSize:'img1FS.jpeg'},
    { id:'2',type: 'painting',size: '180x120',title: 'Spring2', year: '2021', technique: 'Acrilic',location: 'img2.jpeg',locationFullSize:'img2FS.jpeg'},
    { id:'3',type: 'painting',size: '140x90',title: 'Fanovi kraljice gabora', year: '2022', technique: 'Oil',location: 'img6.jpeg',locationFullSize:'img6FS.jpeg'},
    { id:'4',type: 'painting',size: '140x90',title: 'Ljubavnici', year: '2020', technique: 'Oil',location: 'img9.jpeg',locationFullSize:'img9FS.jpeg'},
    { id:'6',type: 'painting',size: '140x90',title: 'Ljubavnici', year: '2020', technique: 'Oil',location: 'img7.jpeg',locationFullSize:'img7FS.jpeg'},
    { id:'7',type: 'painting',size: '140x90',title: 'Ljubavnici', year: '2020', technique: 'Oil',location: 'img8.jpeg',locationFullSize:'img8FS.jpeg'},
    { id:'8',type: 'painting',size: '140x90',title: 'Ljubavnici', year: '2020', technique: 'Oil',location: 'img10.jpeg',locationFullSize:'img10FS.jpeg'},
    { id:'10',type: 'painting',size: '120x100',title: 'Spring3', year: '2022', technique: 'Acrilic',location: 'img11.jpeg',locationFullSize:'img11FS.jpeg'},
    { id:'11',type: 'painting',size: '120x100',title: 'Spring3', year: '2022', technique: 'Acrilic',location: 'img12.jpeg',locationFullSize:'img12FS.jpeg'},
    { id:'12',type: 'painting',size: '120x100',title: 'Spring3', year: '2022', technique: 'Acrilic',location: 'img13.jpeg',locationFullSize:'img13FS.jpeg'},
    { id:'13',type: 'painting',size: '120x100',title: 'Spring3', year: '2022', technique: 'Acrilic',location: 'img14.jpeg',locationFullSize:'img14FS.jpeg'},
    { id:'14',type: 'painting',size: '120x100',title: 'Spring3', year: '2022', technique: 'Acrilic',location: 'img15.jpeg',locationFullSize:'img15FS.jpeg'},
    { id:'15',type: 'painting',size: '120x100',title: 'Spring3', year: '2022', technique: 'Acrilic',location: 'img16.jpeg',locationFullSize:'img16FS.jpeg'},
    { id:'16',type: 'painting',size: '120x100',title: 'Spring3', year: '2022', technique: 'Acrilic',location: 'img17.jpeg',locationFullSize:'img17FS.jpeg'},
    { id:'17',type: 'painting',size: '120x100',title: 'Spring3', year: '2022', technique: 'Acrilic',location: 'img18.jpeg',locationFullSize:'img18FS.jpeg'},
    { id:'18',type: 'painting',size: '120x100',title: 'Spring3', year: '2022', technique: 'Acrilic',location: 'img19.jpeg',locationFullSize:'img19FS.jpeg'},
    { id:'5',type: 'painting',size: '120x100',title: 'Spring3', year: '2022', technique: 'Acrilic',location: 'img20.jpeg',locationFullSize:'img20FS.jpeg'},
    { id:'9',type: 'painting',size: '120x100',title: 'Spring3', year: '2022', technique: 'Acrilic',location: 'img21.jpeg',locationFullSize:'img21.jpeg'},
    { id:'19',type: 'painting',size: '120x100',title: 'Spring3', year: '2022', technique: 'Acrilic',location: 'img3.jpeg',locationFullSize:'img3FS.jpeg'},
    { id:'20',type: 'painting',size: '120x100',title: 'Spring4', year: '2023', technique: 'Acrilic',location: 'img4.jpeg',locationFullSize:'img4FS.jpeg'},
    { id:'21',type: 'painting',size: '120x100',title: 'Spring4', year: '2023', technique: 'Acrilic',location: 'img5.jpeg',locationFullSize:'img5FS.jpeg'},
    { id:'23',type: 'wop',title: 'Spring4', year: '2023', technique: 'Acrilic',location: 'img34.jpeg'},
    { id:'24',type: 'wop',title: 'Spring4', year: '2023', technique: 'Acrilic',location: 'img35.jpeg'},
    { id:'25',type: 'wop',title: 'Spring4', year: '2023', technique: 'Acrilic',location: 'img36.jpeg'},
    { id:'26',type: 'wop',title: 'Spring4', year: '2023', technique: 'Acrilic',location: 'img37.jpeg'},
    { id:'27',type: 'wop',title: 'Spring4', year: '2023', technique: 'Acrilic',location: 'img38.jpeg'},
    { id:'28',type: 'wop',title: 'Spring4', year: '2023', technique: 'Acrilic',location: 'img39.jpeg'},
    { id:'29',type: 'ceramics',title: 'Spring4', year: '2023', technique: 'Acrilic',location: 'img41.jpeg'},
    { id:'30',type: 'ceramics',title: 'Spring4', year: '2023', technique: 'Acrilic',location: 'img42.jpeg'},
    { id:'31',type: 'ceramics',title: 'Spring4', year: '2023', technique: 'Acrilic',location: 'img43.jpeg'},
    { id:'32',type: 'ceramics',title: 'Spring4', year: '2023', technique: 'Acrilic',location: 'img44.jpeg'},
    { id:'33',type: 'bio-image',location: 'bio-image.jpeg'}
  ]
  return art;
}